### ISSUE TITLE
not support CocoaPods 1.x

### ISSUE THREAD

**Issue by daviyang35** [fatuhoku/demo-modular-ios-with-cocoapods-frameworks-and-xcprojects#1]
when execute
$pod install

[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `RootProject`..

 #  from /Users/daviyang/Desktop/demo-modular-ios-with-cocoapods-frameworks-and-xcprojects-master/Podfile:7
 #  -------------------------------------------
 #

>  target :RootProject, :exclusive => true do
>  #      xcodeproj 'RootProject/RootProject.xcodeproj'
>  #  -------------------------------------------

[!] xcodeproj was renamed to `project`. Please use that from now on.

**Comment by daviyang35** [comment]
the right Podfile

``` ruby
workspace 'Root.xcworkspace'

# project defined here to avoid 'Could not automatically select an Xcode project' error.
# See https://github.com/CocoaPods/CocoaPods/issues/738#issuecomment-49497948
project 'RootProject/RootProject.xcodeproj'

target :RootProject do
    project 'RootProject/RootProject.xcodeproj'
end

target :Project1 do
    project 'Project1/Project1.xcodeproj'
end

target :Project2Framework do
    pod 'BOString'
    project 'Project2/Project2.xcodeproj'
end
```

**Comment by hokster7** [comment]
Hey @daviyang35 despite setting up this project, I would actually really recommend against using Cocoapods to organise your project's build process. It's slow and locks you in to the Cocoapods ecosystem.
